[project]
name = "musti-data-engineer-assignment"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "duckdb>=1.3.2",
    "openpyxl>=3.1.5",
    "pandas>=2.3.2",
]
